### ISSUE TITLE
Unable to build my blog

### ISSUE THREAD

**Issue by jruaud** [scripting/drummerSupport#104]
I've been unable to build my blog due to an error. Using the "Build my blog..." , I see the following dialog/error dialog:
![image](https://user-images.githubusercontent.com/97596/139558403-500b5690-0de6-4985-9867-6495851ff12e.png)
And the console :
getFilestatsForNewInactiveTab: options.filestats == {
    "size": 1112,
    "whenAccessed": "Sat, 30 Oct 2021 20:35:26 GMT",
    "whenCreated": "Sat, 30 Oct 2021 20:31:43 GMT",
    "whenModified": "Sat, 30 Oct 2021 20:34:37 GMT",
    "title": "About",
    "dateCreated": "Sat, 30 Oct 2021 20:31:43 GMT",
    "dateModified": "Sat, 30 Oct 2021 20:34:37 GMT",
    "ownerTwitterScreenName": "RuaudJean",
    "ownerName": "Jean RUAUD",
    "ownerId": "http://twitter.com/RuaudJean",
    "urlUpdateSocket": "ws://drummer.scripting.com:1232/",
    "expansionState": "1",
    "lastCursor": "5",
    "flPublic": "true",
    "urlPublic": "http://drummer.scripting.com/RuaudJean/About.opml"
}
code.js:2889 startScriptsMenu: there is no menubar.opml file.
VM165 :1 Access to XMLHttpRequest at 'http://drummercms.scripting.com/build?blog=RuaudJean' from origin 'http://drummer.scripting.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
code.js:1463 alertDialog: inserting the dialog into the dom.
drummercms.scripting.com/build?blog=RuaudJean:1 Failed to load resource: net::ERR_FAILED
code.js:3961 wsConnectToServer: msg == user 1103966256753971200-Ek23166k4da1H2L0slKJIcA2KYNfyI iyiPNhPjToO5CULoXUZ7KiPCCTEepVAQgCaUinQpfolu5

**Comment by scripting** [comment]
@jruaud -- thanks for the report. please try again and let me know if it works.

**Comment by jruaud** [comment]
I tried again, it doesn't work.

**Comment by scripting** [comment]
@jruaud -- try again.

**Comment by jruaud** [comment]
Still an error.

**Comment by scripting** [comment]
The problem is that your glossary is empty. Drummer should be able to handle it, but I can't at this time change the server software. The best thing to do is to delete the urlGlossary head element, and things will probably start working.

**Comment by jruaud** [comment]
Ok, it was that, all is normal now, thanks!
👍
