### ISSUE TITLE
Get permalink of selected publish outline in scripting?

### ISSUE THREAD

**Issue by frankmeeuwsen** [scripting/drummerSupport#108]
When I publish a post on Drummer, I sometimes want to post it to my regular WordPress blog as well. I want to include a link back to the Drummer blog as well. I use my own [Publish to WordPress script](http://oldschool.scripting.com/frankmeeuwsen/2021/10/23/065437.html?title=publishToWordpressWithDrummer) to do this. I want the script to automatically add a line at the end of the text saying (Originally posted at http://oldschool.scripting.com/frankmeeuwsen/HERE-BE-URL)

Is there a way to get the public URL of a published blogpost in the scripting environment, based on the location of the cursor? The cursor is placed on the main outline node of the blogpost (most of the times the title of your post)

I searched the docs but couldn't find anything that helps me with my question. I thought maybe op.getCursorOpml() or opml.getCurrentObject () might give some info on the published URL but unfortunately not. Any help is appreciated.

**Comment by scripting** [comment]
@frankmeeuwsen -- Drummer and Old School are different pieces of software, so Drummer doesn't even know really that your outline is used for a blog. But you can compute the URL on your own. 

Here's an example.

http://oldschool.scripting.com/frankmeeuwsen/2021/11/09/113021.html?title=oudeNotitieboeken

You don't have to provide the part after the ?, that's just used to make the URL more human-readable.

The only part that isn't obvious is 113021.html.

For that you can just do what Old School does. 

https://github.com/scripting/oldSchoolBlog/blob/master/oldschool.js#L444

It's a function of the created attribute of the post.

Hope this helps.

**Comment by frankmeeuwsen** [comment]
Oh yes this helps! I can work with these pointers, thanks!
