### ISSUE TITLE
(Still?) a timezone problem

### ISSUE THREAD

**Issue by frankmeeuwsen** [scripting/drummerSupport#112]
I am aware of all the timezone problems in Drummer the last couple of weeks. I've followed in on the sideline a bit. I am under the impression everything should work again in all timezones, yet I still have an issue I found this morning. 

- I am in The Netherlands, we are on UTC+01:00 right now
- I made [a new post](http://oldschool.scripting.com/frankmeeuwsen/2021/11/13/082844.html?title=hereIsAPostWithATitle) with a title just now (9:28 AM) and published it
- The Created attribute of the title says it's created on 8:28 AM
- So does the last part of the URL of the post.
- I have an OPML header timeZoneOffset with +1
- I also [made a script](https://gist.github.com/frankmeeuwsen/12c724427ee2e2b9593428e749c67050) to get the date, show it in an alert and open the URL. This shows the correct time in the alert from my timezone (9:28 AM) but that doesn't reflect what's in the Created attribute.

So what's the best way forward? Update my script with a -1 in the Hour-part? Or is there still a timezone bug?

**Comment by scripting** [comment]
@frankmeeuwsen — the problems we fixed have to do with the rendering of blogs, on a server that’s in the US. Not sure what the problem us here, or if there even is a problem. If you want help you have to explain more carefully.

**Comment by scripting** [comment]
BTW -- this is the code that sets the created attribute of new headlines.

`atts.created = new Date ().toUTCString (); `

There's not a whole lot that can go wrong there.

I read your comment carefully twice, and I don't a report of a problem there.

**Comment by frankmeeuwsen** [comment]
@scripting I've been out all day, but thanks for your feedback. I just made another post with some screenshots. I'll try to be as precise as possible. First my current setup
1. I am in the Netherlands, we are currently on GMT+1 (See https://www.timeanddate.com/worldclock/netherlands/amsterdam)
2. So in my OPML headers, I have had the attribute timeZoneOffset set to +1 since this was possible. (See screenshot)

<img width="1033" alt="Screenshot-Drummer-20211113191503" src="https://user-images.githubusercontent.com/1940855/141654712-8bedbec4-4ec9-4ac9-9b13-b5b7a0de0a95.png">

3. I want to get the permalink for a post so I can use it in other places. As you explained in #108 It is possible to build the URL based on the date and time. 
4. I made a script that does exact this. You can see this in [this gist](https://gist.github.com/frankmeeuwsen/12c724427ee2e2b9593428e749c67050).
5. Here is what happens. I made [a new post](http://oldschool.scripting.com/frankmeeuwsen/2021/11/13/180509.html?title=heresAnotherPostToExplainTheProblem) at 19:05 Dutch time. You can already see in the URL it is one hour behind.  The end part of the URL, as I understand from your explanation in #108, is build on the hour, minute and second. 
6. When I publish the post at 19:05 PM, the attribute for "created" also says it is created on 18:05
<img width="901" alt="Screenshot-Drummer-20211113190559" src="https://user-images.githubusercontent.com/1940855/141654671-43bfd10c-ae72-4b2d-8d3b-f088edb12ec3.png">

7. The attribute "created" should say 19:05 PM. Since this is the time it is created. 
8. When I run [the script](https://gist.github.com/frankmeeuwsen/12c724427ee2e2b9593428e749c67050) on this post, the alert gives me the correct time! Which is actually weird, since the attribute for "created" is one hour behind as you see in the screenshot above, 

<img width="827" alt="Screenshot-Drummer-20211113192204" src="https://user-images.githubusercontent.com/1940855/141654964-572e8c3e-4a17-4ec1-ad58-8a1d84522349.png">

9. What happens is when I use the date from this script to build the URL, it is the correct URL for when the post is _actually_ created (19:05) but since the permalink in the built blogpost is one hour behind (18:05) I get a 404 when I open the URL from [this script](https://gist.github.com/frankmeeuwsen/12c724427ee2e2b9593428e749c67050).

What I would expect is in step 8 above, the script would give me the (actually wrong) hour as is shown in the "Created" attribute: 18. Instead it gives me 19. Which is the correct hour. 
But! [The URL](http://oldschool.scripting.com/frankmeeuwsen/2021/11/13/180509.html?title=heresAnotherPostToExplainTheProblem) that Drummer or OldSchool has made is not correct, it is actually one hour behind. It ends with 180509 when it should say 190509

It gets even weirder I just found out. Here's [another script](https://gist.github.com/frankmeeuwsen/b8a46c1f2a83769b29f9386faa002a6a) to just show me the hour from the Attribute "created".
When I run this, I first get an alert: "Sat, 13 Nov 2021 18:05:09 GMT"
The next alert is "2021/11/13/190509.html"
You see how 18 suddenly turns into 19? 
Maybe I don't understand date formatting in Javascript. As I said before, I'm a poet not a plumber ;-) But what am I missing here?

I hope this explains the issue some more.

**Comment by scripting** [comment]
Maybe someone else can help, i have to do other things and i'm guessing this is either a misunderstanding of what GMT means, or something is incorrectly configured on your system -- but sometimes to solve software problems you have to stare at it, and think a lot and challenge your assumptions, and learn about something new or whatever. i do it all the time frank, and i don't bring problems to other developers until i'm absolutely sure the problem is with their software and i can give them reproducible steps.

**Comment by am1t** [comment]
@frankmeeuwsen I [had created](https://www.amitgawande.com/2021/10/23/getting-post-url.html) a [similar script](https://gist.github.com/am1t/c1a1d37af7cd33aedc9e1263888a70e0) to do a very similar thing, continues to work for me. Can you try it for your setup?

**Comment by frankmeeuwsen** [comment]
@am1t This is _exactly_ what I was looking for. I see what I'm doing different in your script. You use getUTCHours() whereas I use string.formatDate(). I think there is the problem on my part. I never knew about getUTCHours() well enough so I learned something as well. Thanks!
