### ISSUE TITLE
Eye Icon 404 error on Drummer Change notes OPML

### ISSUE THREAD

**Issue by sabre23t** [scripting/drummerSupport#113]
When using the Eye Icon on Drummer Change notes OPML as below ...
<img src="https://user-images.githubusercontent.com/205024/141759774-7ded9086-72c2-4ee3-b172-d0b4c13b2050.jpg" width=70%>

It opens a link http://scripting.com/drummer/blog/2021/11/15.html#a233427 that gives **404 Not Found** error.

It should open the link http://scripting.com/drummer/blog/2021/11/14/233427.html?title=oldschoolgetcursorlinkVerb instead.

I'm user sabre23t in timezone MYT +8.

**Comment by scripting** [comment]
There’s a use-case I didn’t consider. 🙀

**Comment by scripting** [comment]
@sabre23t -- thanks for the excellent report. 

I believe I have the problem fixed, and you should be able to click the Eye icon in the Change Notes outline to go to the web page version of a post.

Please let me know if it works.

**Comment by scripting** [comment]
@sabre23t — please let me know if this issue was resolved.

**Comment by sabre23t** [comment]
@scripting I've tried using the Eye Icon quite a bit on Drummer Change Notes this morning to create links in my blog. I found it works well now. TQ.
