### ISSUE TITLE
How to edit template (index.html?) to reference public image URL?

### ISSUE THREAD

**Issue by ken-hall** [scripting/drummerSupport#115]
Newbie question.  Using Drummer on the web (PC- Chrome) while waiting for my first Mac in a long long time (since Lisa and Mac 128K!).  Being the designer type i want to change the header image.  Have looked through the Blogger page and believe I need to edit the head level attribute of Index.html- but so far I cannot figure out how to locate/edit this file. 

I am an old user of More and Frontier, but it has been awhile since i edited web pages.  All clues welcome. Still digging...

**Comment by scripting** [comment]
@ken-hall — welcome back to outlineland 😀

You just set the head-level attribute in blog.opml. 

There’s nothing else to find.

**Comment by ken-hall** [comment]
[Got it!](http://oldschool.scripting.com/kenhall88/)  It was just too simple and obvious! :)
Thank you!
