### ISSUE TITLE
Drumkit docserver OPML location?

### ISSUE THREAD

**Issue by PostMonsterG** [scripting/drummerSupport#118]
I'm making myself an icon that looks up highlighted terms in docserver, and I found myself wanting a list of available Drumkit verbs.

I assume this is in OPML somewhere, is there an outline I can subscribe to?

Just in case it's useful for anyone else, here's a simple version of the icon. 

```
times
	var term = string.trimWhitespace(op.getSelectedText());
	if (string.countFields(term, ".") == 2) {
		webBrowser.openUrl ("http://docserver.scripting.com/?verb=" + term); 
	} else {
		speaker.beep();
		}
```

**Comment by scripting** [comment]
@PostMonsterG — that’s on my list, I want it too. I

**Comment by scripting** [comment]
BTW, there is a list of all the verbs, in the menu in DocServer. 

![image](https://user-images.githubusercontent.com/1686843/142746460-5433d0c5-4c4d-478b-bf57-308552eac196.png)

**Comment by PostMonsterG** [comment]
The docserver lists don't scroll on the iPad, so I can't see the ones at the bottom that way.

Actually, I wanted it in opml so I could do smarter lookup for my docserver caller, and possibly enable things like autocomplete or refactoring. I like coding in Drumkit so far, but I already miss things like option-click a symbol to go to the definition, etc

**Comment by PostMonsterG** [comment]
The gist provided at https://gist.github.com/scripting/8e0b74bc144e88ab6c38e6d0be3ab049 helped a lot. I've updated the my docserver lookup Drumkit linked in my previous comment so it validates against the actual verbs before attempting a lookup, which makes it way more useful. 

Also I am refining my approach to Drumkit now that I understand its scoping a bit more.

Right now the DocServer site is broken on my iPad, it is throwing exceptions and isn't rendering the docs properly. But I'm pretty sure the script works OK.

There's also a commented-out experiment which attempts to open a tab and scroll to the right entry. The tab opening works, but I don't think the op verbs will let me navigate and expand nodes in that tab over there.
