### ISSUE TITLE
Changing outline status from Public to Private, changing outline status from Read-Write to Read-Only

### ISSUE THREAD

**Issue by DLuebbert** [scripting/drummerSupport#120]
I experimentally gave one of my outlines Public status using the "Make outline public..." command, expecting that there would be some method available to change it back to Private status. Really expected that this status would be toggleable using a "Make outline public/private..." command. I haven't found an option in the interface that would allow one to accomplish this. Currently, making something Public seems to be an unalterable decision. 

Could you show how one makes a Public outline Private?

Also, to create an outline it does seem that it is absolutely necessary that it be created with Read-Write status. At the moment it is published though, it seems that it should be set by default to read-only status, in order to prevent a reader from deciding to revise an outline design that the author spent a lot of time putting in place. At the very least, it seems a reader revision should require the author's permission before it is allowed to become part of a published outline. 

Can you show how one can change an outline's status from Read-Write to Read-Only and vice versa?

Thanks!

**Comment by scripting** [comment]
@DLuebbert -- nice to see you here! ;-)

1. There is no way to make an outline private after it has been made public. The thought is that in reality once something is public it's out there and nothing is going to bring it back. You can delete the file and create it again, and the new file will be private. I'll take this as a feature request. 

2. There is no way to make an outline read-only. All outlines you create are read-write. Outlines that you subscribe to, that are authored by someone else, are read-only. Those are the only read-only files in Drummer.

**Comment by DLuebbert** [comment]
Thanks, Dave, I really enjoy using your software and finding out what it can do;-). I'll try to provide feedback as you work to tune it for widest public use. 

About the unpublishing query:

OK, when I need to backout of a publishing attempt, I can save my opml locally via Tools/Download my files.., delete the errantly published opml document from Drummer, create an empty opml doc using the just deleted name and then reestablish that outline using File/import local file...

I've verified for myself that this does what I need. 

Would deleting "flPublic" and "urlPublic" from the top-level attributes of my opml doc, constitute unpublishing the opml, or are those not being watched in deciding if an outline is published or not? 

I've tried this for one of my public outlines, and find that it is still considered to be public by Drummer even when I've deleted these attributes.

If this kind of functionality worked, probably wouldn't want/need to clutter "Make outline public..." with an unpublishing option to handle this rare case.

About the read-write/read-only confusion I had:

I got the wrong idea about how outline read-write and read-only states might work by hovering above the status icons that appear to the left of my outline titles on my Drummer outline editing tabs. 

 When I hover over the status icons of my publicized outlines that have been made public,  I see that their status is reported as "Public, Read-Write". When I hover above the status icons for "Changes notes" and "Old School.js", I see their status is reported as "Public, Read only" and that they have snazzy World and Lightning bolt icons instead of the document icon I see for my own outlines. 

Having seen that, my reaction was that I wanted my published outlines to have the same or similar treatment that "Change notes" and "Old School.js" had been granted. Also I became  alarmed that the public might have been granted my editing rights during the switch of the outline to Public access.  

Maybe it would make sense to report the right to edit that the author still retains after the outline is published and also the Read-only status that members of the public will experience as they view it. 

Seems like this might be an important distinction to express when an outline is used as an Instant Outline, where the author, selected members of an editing group, and/or members of the public might be given permission to write in the outline.

Perhaps status icons of public outlines could report  something like "Status: Public, Read-Write for Author,  Read only for Public".

When an outline is used as an Instant Outline, a status report might might show options that could be granted in different combinations like this:

"Status: Read-Write/Read only for Author, Open/Closed access, Read-Write/Read only for Editing group, Closed/Open access, Read-Write/Read-only for Public"

New query:

I'd like to learn how to publish one of the opml outlines I've created with Drummer on my own sites, with the opml having the open/collapse functions and display polish that I see that you have activated within your http://docserver.scripting.com/drummer/ subsite. 

Is there a recipe written that shows how to do this? 

I think the kind of OPML presentation you are doing there should be available to add to any site on the web, if you can figure out how to make that happen. I suspect you already know most or all of what's necessary. The payoff to the web's development could be huge if you can do this. 

Using Drummer's OPML docs to document software, I try to structure docs so that readers can get a top-level overview of what my software does by scanning whatever upper levels of the outline I decide should be left open for first viewing. 

I leave lower sections of the outline collapsed to hide descriptions of software operation and user interaction.

 When a reader comes to suspect it might pay off to learn how things work that are discussed in some part of the outline, they can click into the lower outline levels that are collapsed in that vicinity to find what they need to know. 

Using this kind of structure, one can protect a reader from being exposed to a blizzard of details about a project whose significance they don't yet understand before they can get oriented and can start to understand how things in the project might fit together.

**Comment by DLuebbert** [comment]
Dave, I  finally did figure out that getting PagePark up on my servers is key for getting opml files to serve in the pretty fashion I was asking for in my last query. 

Really slick how that all works.
