### ISSUE TITLE
Error in http.client with ia-writer urls

### ISSUE THREAD

**Issue by PostMonsterG** [scripting/drummerSupport#121]
Drummer v2.0.11
iPad 15.1, Safari

# Steps to reproduce

```
//    Simple test code for communicating with iA Writer
	const request = {
		type: "GET",
		url: "ia-writer://x-callback-url/write",
		params: {
			path:            "/Locations/On My iPad/Drummer Files/test.txt",
			"auth-token":    "[redacted]",
			mode:            "replace",
			text:            "Howdy momo",
			},
		};
		
	http.client( request, false )
```
	
# What happens
```
runScriptText: processedScriptText == (async function () {const request = {
    type: 'GET',
    url: 'ia-writer://x-callback-url/write',
    params: {
        path: '/Locations/On My iPad/Drummer Files/test.txt',
        'auth-token': '[redacted]',
        mode: 'replace',
        text: 'Howdy momo'
    }
};
await http.client(request, false);})()
null
```

The URL being constructed looks correct: `ia-writer://x-callback-url/write?path=%2FLocations%2FOn%20My%20iPad%2FDrummer%20Files%2Ftest.txt&auth-token=[redacted]&mode=replace&text=Howdy%20momo`

# What should happen

Opening the URL in Safari's address bar creates a file in iA Writer

**Comment by scripting** [comment]
@PostMonsterG -- not sure what the intention is here, you don't say -- you've posted some code. beyond that, i don't see an issue.

**Comment by PostMonsterG** [comment]
I'm sorry, the "null" in the console output is from an exception. The URL never gets called, ia-writer doesn't get contacted.

The url that is constructed is OK, if you manually paste it into Safari, it works. So the problem is in the http client code, it is throwing an error instead of actually calling the URL.

**Comment by scripting** [comment]
ia-writer://x-callback-url/write doesn't look like an http url to me. maybe i'm missing something.

**Comment by scripting** [comment]
BTW, this is the message when I tried opening it in safari.

![image](https://user-images.githubusercontent.com/1686843/143088661-67fea1f0-9d61-48ac-bf45-b328274b646b.png)

**Comment by scripting** [comment]
Chrome didn't even give a message, they just interpret it as a search request. 

What made you think that was supposed to be an HTTP url????

**Comment by PostMonsterG** [comment]
Oh I am so sorry, I really screwed up explaining this.

If you have iA Writer installed, that URL will open iA Writer. I am not sure the mechanism, it works on the iPad, and according to the iA Writer docs, should also work on macOS.

The auth token is something you get from iA Writer, which tells iA Writer this request is OK to handle.

iA Writer provides a few different actions using this mechanism. You can create a new file, read, write, append files.

You can test these URLs by the address bar in Safari. I have a Drumkit script that uses `webBrowser.openURL` to create a new document with up to 4K of contents, which has been super handy for previewing Markdown.

To handle larger files, and to read the file back, I need something I can call repeatedly in 4K chunks. The `webBrowser.openURL` call results in a "Open in “iA Writer”?" dialog box from Safari, confirming if it's OK to open the link.

I guess I was hoping that Drummer would be routing through whatever mechanism that the iPad/macOS is using to intercept `ia-writer` url schemes. Now that I think about it, "http" is right there in the name `http.client`, so, duh.

Again, I am sorry I wasted your time by not being more clear. I know better, I need to slow down sometimes.

**Comment by PostMonsterG** [comment]
Here is a link to the Drumkit that sends the text of the current outline to iA Writer. It doesn't require an auth token, and has been working great so far. Very handy for hoisted outline chunks. I've been using it for Markdown previews and search/replace for Drumkit code.

http://drummer.scripting.com/PostMonsterG/OpenInIAWriterAsNewFile.opml
