### ISSUE TITLE
"File → New..." does not check if filename is already used.

### ISSUE THREAD

**Issue by papascott** [scripting/drummerSupport#122]
"File → New..." lets me create a new outline with the same filename as an existing outline. The new file appears to be saved, but is in fact never saved. The existing outline is preserved. 

- I have an existing ~private~ public outline 'temp.opml'
- With "File → New..." I create a new outline with the name 'temp.opml'
- A tab opens with a new empty outline. I type in some text, the saved status above the outline changes to NOT SAVED, then a couple of seconds later to SAVED
- I close the tab
- I open 'temp.opml' with "File → Open". It opens the previously existing outline "temp.opml". The new "temp.opml" is gone.

Here's the console output.
```
activateThisOutline: options.filestats == {
    "title": "temp",
    "dateCreated": "Tue, 23 Nov 2021 13:56:59 GMT",
    "dateModified": "Tue, 23 Nov 2021 13:56:59 GMT",
    "whenCreated": "Tue, 23 Nov 2021 13:56:59 GMT",
    "whenModified": "Tue, 23 Nov 2021 13:56:59 GMT",
    "size": 300
}
code.js:947 saveThisTab: f == temp.opml, secs == 0.363, secs since interact == 0.145
code.js:947 saveThisTab: f == temp.opml, secs == 0.131, secs since interact == 1.488
code.js:947 saveThisTab: f == temp.opml, secs == 0.248, secs since interact == 0.017
code.js:947 saveThisTab: f == temp.opml, secs == 0.123, secs since interact == 1.133
code.js:947 saveThisTab: f == temp.opml, secs == 0.128, secs since interact == 1.577
code.js:866 activateThisOutline: options.filestats == {
    "size": 1746,
    "whenAccessed": "Tue, 23 Nov 2021 11:00:03 GMT",
    "whenCreated": "Sun, 21 Nov 2021 10:41:02 GMT",
    "whenModified": "Sun, 21 Nov 2021 11:00:02 GMT",
    "title": "temp",
    "dateCreated": "Sun, 21 Nov 2021 10:41:02 GMT",
    "dateModified": "Sun, 21 Nov 2021 11:00:02 GMT",
    "ownerTwitterScreenName": "ScottHansonDE",
    "ownerName": "Scott Hanson",
    "ownerId": "http://twitter.com/ScottHansonDE",
    "urlUpdateSocket": "ws://drummer.scripting.com:1232/",
    "expansionState": "1,2,7",
    "lastCursor": "7",
    "flPublic": "true",
    "urlPublic": "http://drummer.scripting.com/ScottHansonDE/temp.opml"
}
```

**Comment by scripting** [comment]
@papascott -- thanks for the excellent report. obviously that is a very wrong thing for the software to do. 

here's a guess -- the first version of the file is public.

**Comment by papascott** [comment]
@scripting You're right... it was public. I thought it was private, but looking at the console output I pasted in I see it had "flPublic": "true" in the attributes. I'll try it again with a private file and see what happens.

**Comment by scripting** [comment]
@papascott -- you don't need to do that. I have enough info.

The reason the new file didn't replace the old one is that public and private files are stored in different locations. 

New files are private. 

When opening a file we look for the public one first.

But the mistake was real either way -- you should not be allowed to create a file that already exists, at least not without a warning that you're doing so.

**Comment by scripting** [comment]
@papascott -- this should be fixed now, please verify it now works as it should on your machine.

**Comment by papascott** [comment]
@scripting Same scenario, tried to create a new outline with the same name as an existing public outline, got a dialog "Can't create "temp.opml" because there already is a file with that name." 👍
