### ISSUE TITLE
Posting code snippets

### ISSUE THREAD

**Issue by cro** [scripting/drummerSupport#141]
Is there any way to include code snippets in various languages in a monospace font?  I have a vague recollection of Dave mentioning this somewhere but I can't find it now.  Ideally this would include syntax highlighting.

**Comment by scripting** [comment]
The attribute is flCodeSubs.

http://daytona.scripting.com/?q=flcodesubs&collection=drummerdocs

You'll find the docs on the Blogging howto page, linked to from the Docs menu.

**Comment by cro** [comment]
This works!

**Comment by cro** [comment]
One more question, I notice there are references in the docs to embedding YouTube videos.  Would it be possible to embed GitHub gists in a similar way?

**Comment by scripting** [comment]
@cro -- it's an interesting idea -- I started a thread here. This site is just for support.

https://github.com/scripting/drummerRFC/issues/15
