### ISSUE TITLE
Blog contents duplicated

### ISSUE THREAD

**Issue by cro** [scripting/drummerSupport#142]
Greetings,

While experimenting with moving some blog content into Drummer I am getting content duplicated on the generated blog page.  The content is not duplicated in the OPML text or in Drummer itself.  Did I do something wrong?

Here is the generated blog: http://oldschool.scripting.com/croldham/

Here is the opml: http://drummer.scripting.com/croldham/blog.opml

**Comment by am1t** [comment]
I don't see any duplicate content. Have you tried hard reload?

**Comment by scripting** [comment]
@am1t -- glad you checked in here. I think there's something going on here related to the rollover feature, where you can delete the contents of your blog,opml and start fresh without wiping out the contents of your home page.

If you look at the dates of his posts, it looks like he's restoring a blog using Drummer, and my guess is he probably changed the date on one or more posts, and Old School thought "OK this is cool, I can find more posts in the cache" and it did. 

Here's a [screen shot](https://user-images.githubusercontent.com/1686843/146644357-8ce24d8c-ce6a-43f9-bade-3599fac214d2.png) of his cache on the server. 

Anyway -- @cro -- there's not much you can do about this, I could wipe out the cache for you, but I'd rather not do it. Could cause unpredictable results. A safer approach would be to leave the old stuff there, and keep using the blog, and after 25 posts the extra stuff will scroll off the bottom. 

And the lesson here is you have to be careful about changing the dates on posts, if that's what happens. Do it before you do a build, not after.

**Comment by am1t** [comment]
Hmm, now I see it. Thank you for that explanation, Dave. I wasn't aware of how caching worked with Old School. 
This one looks to be an edge case, I guess.

**Comment by cro** [comment]
That fits my use case.  I'm not doing a bulk import; I have so few blog entries I was entering them by hand to get used to the Drummer interface.  I was adding text, then building the blog to see how it would render.  I changed dates a lot in there to make the entries line up with their original post date.  I'm not sure if I have a total of 25 posts 😂 , but I will keep plugging along.

**Comment by scripting** [comment]
Here's the docs on caching. 

http://daytona.scripting.com/?q=caching&collection=drummerdocs
