### ISSUE TITLE
Use of tab.openFile creates apparent tab overwriting

### ISSUE THREAD

**Issue by andysylvester** [scripting/drummerSupport#143]
# Executive Summary

Use of the verb tab.openFile does not open a new file and causes apparent tab overwriting, but does not result in data loss. However, given the recent activity to identify a set of steps to cause actual tab overwriting, I decided to capture steps to reproduce this problem in the hope that it would help with the other problem.

# Initial work

I decided to try to reproduce Gary Teter’s TabMonster problem (https://github.com/scripting/drummerSupport/issues/119), I was able to do it, posted some info on that issue. One thing I noticed is that I tried to close the weird tab using File – Close, it actually closed the original tab/content. I also had another tab open. I clicked over to that tab (notes.opml), then back to the TabMonster tab, and the contents of the TabMonster tab now had the content of notes.opml.

After that, I decided to organize a repeatable set of steps for this instance of apparent file/tab overwriting.

# Steps to reproduce and document problem 

Went to http://drummer.scripting.com/ in Google Chrome, Drummer came up as I was already logged in.

Did a hard reload per these instructions (http://docserver.scripting.com/drummer/general.opml#1633017426000), confirmed that Drummer version was v2.0.12.

Opened Developer Tools in the Drummer browser tab.

Closed all open tabs, then opened three previously created private OPML files with different text (tabtest01.opml, tabtest02.opml, tabtest03.opml) and a fourth private file (notes.opml) containing text with the tab name “Notes”. The order of the tabs was Notes, tabtest01.opml, tabtest02.opml, tabtest03.opml.

Added the following headline to tabtest01.opml:

tab.openFile("TabSmasher.opml")

Placed the cursor on that headline, then selected Reorg – Run selection to execute that one line of Javascript. When I took that action, a tab called TabSmasher opened containing the contents of tabtest01.opml. The TabSmasher tab did not have a close control.

![image](https://user-images.githubusercontent.com/6290758/146656840-edaa9391-5566-4bf5-8948-009daaf13b10.png)

In the screen capture, the tabtest01 tab and the TabSmasher tab appear to be both active at the same time. The Javascript console indicates there was an error in opening the new tab.

The console text was as follows:

runScriptText: processedScriptText == (async function () {await processRunCursorScriptResult(await tab.openFile('TabSmasher.opml'), 1);})()
jquery-1.9.1.min.js:5 GET http://drummer.scripting.com/getfile?oauth_token=1302741194351411200-KtaMuteCIb6aN8V0DmxUBy9jfSpMrQ&oauth_token_secret=xKOWFiRMMi6bgmrpnYoZblDb8P3PT9DyY41lT4rrQo1u0&relpath=TabSmasher.opml&flIncludeBody=true 500 (Internal Server Error)

send                          @ jquery-1.9.1.min.js:5
ajax                           @ jquery-1.9.1.min.js:5
twGetFile                  @ api.js:362
drummerGetFile       @ code.js:386
downloadFile            @ code.js:1738
getOutlineOpmltext  @ code.js:591
activateThisOutline   @ code.js:900
newOutlineInTab      @ code.js:1209
openOutlineInTab     @ code.js:1278
(anonymous)             @ verbs.js:321
openFile                    @ verbs.js:320
eval                           @ VM634:1
eval                           @ VM634:1
(anonymous)             @ scripting.js:47
runScriptText            @ scripting.js:49
runCursorScript        @ code.js:2613
onclick                      @ (index):1

api.js:369 twGetFile: error == {
    "readyState": 4,
    "responseText": "{\n    \"errno\": -2,\n    \"code\": \"NoSuchKey\",\n    \"syscall\": \"open\",\n    \"path\": \"publicFiles/users/PDXProtestNews/TabSmasher.opml\",\n    \"status\": 500\n}",
    "status": 500,
    "statusText": "Internal Server Error"
}

Clicked on tabtest02.opml tab and tabtest03.opml tab, tab text appeared as expected. 

Console text:

onTabActivate: options.fname == tabtest02.opml  code.js:1442 
onTabActivate: options.fname == tabtest03.opml  code.js:1442 

Clicked on TabSmasher tab, it was selected, but showed the text of tabtest03.opml:

![image](https://user-images.githubusercontent.com/6290758/146656857-5ff82b50-c8f7-48b0-99b5-35ebaab5c96d.png)

Console text:

jquery-1.9.1.min.js:5 GET http://drummer.scripting.com/getfile?oauth_token=1302741194351411200-KtaMuteCIb6aN8V0DmxUBy9jfSpMrQ&oauth_token_secret=xKOWFiRMMi6bgmrpnYoZblDb8P3PT9DyY41lT4rrQo1u0&relpath=TabSmasher.opml&flIncludeBody=true 500 (Internal Server Error)

send                          @ jquery-1.9.1.min.js:5
ajax                          @ jquery-1.9.1.min.js:5
twGetFile                 @ api.js:362
drummerGetFile      @ code.js:386
downloadFile           @ code.js:1738
getOutlineOpmltext @ code.js:591
activateThisOutline @ code.js:900
(anonymous)           @ code.js:1080
dispatch                   @ jquery-1.9.1.min.js:3
v.handle                   @ jquery-1.9.1.min.js:3

api.js:369 twGetFile: error == {
    "readyState": 4,
    "responseText": "{\n    \"errno\": -2,\n    \"code\": \"NoSuchKey\",\n    \"syscall\": \"open\",\n    \"path\": \"publicFiles/users/PDXProtestNews/TabSmasher.opml\",\n    \"status\": 500\n}",
    "status": 500,
    "statusText": "Internal Server Error"
}

Clicked on tabtest02.opml tab, saw text as expected:

onTabActivate: options.fname == tabtest02.opml              code.js:1442 

Clicked on TabSmasher tab, saw text from tabtest02.opml appear in TabSmasher tab.

![image](https://user-images.githubusercontent.com/6290758/146656868-7c249fbf-a212-4cd0-a50e-574d5bd09379.png)

Console text:

jquery-1.9.1.min.js:5 GET http://drummer.scripting.com/getfile?oauth_token=1302741194351411200-KtaMuteCIb6aN8V0DmxUBy9jfSpMrQ&oauth_token_secret=xKOWFiRMMi6bgmrpnYoZblDb8P3PT9DyY41lT4rrQo1u0&relpath=TabSmasher.opml&flIncludeBody=true 500 (Internal Server Error)

send                                  @ jquery-1.9.1.min.js:5
ajax                                   @ jquery-1.9.1.min.js:5
twGetFile                          @ api.js:362
drummerGetFile               @ code.js:386
downloadFile                    @ code.js:1738
getOutlineOpmltext          @ code.js:591
activateThisOutline          @ code.js:900
(anonymous)                     @ code.js:1080
dispatch                             @ jquery-1.9.1.min.js:3
v.handle                             @ jquery-1.9.1.min.js:3

api.js:369 twGetFile: error == {
    "readyState": 4,
    "responseText": "{\n    \"errno\": -2,\n    \"code\": \"NoSuchKey\",\n    \"syscall\": \"open\",\n    \"path\": \"publicFiles/users/PDXProtestNews/TabSmasher.opml\",\n    \"status\": 500\n}",
    "status": 500,
    "statusText": "Internal Server Error"
}

Clicked on tabtest01, tabtest02, tabtest03, Notes, text appeared as expected.

Console text:
code.js:1442 onTabActivate: options.fname == tabtest01.opml
code.js:1442 onTabActivate: options.fname == tabtest02.opml
code.js:1442 onTabActivate: options.fname == tabtest03.opml
code.js:1442 onTabActivate: options.fname == notes.opml

Clicked on TabSmasher tab, saw text from notes.opml appear in TabSmasher tab.

![image](https://user-images.githubusercontent.com/6290758/146656874-0ba5b0ce-c10b-4357-9a83-f7351aa75056.png)

Console text:

GET http://drummer.scripting.com/getfile?oauth_token=1302741194351411200-KtaMuteCIb6aN8V0DmxUBy9jfSpMrQ&oauth_token_secret=xKOWFiRMMi6bgmrpnYoZblDb8P3PT9DyY41lT4rrQo1u0&relpath=TabSmasher.opml&flIncludeBody=true 500 (Internal Server Error)

send                                @ jquery-1.9.1.min.js:5
ajax                                 @ jquery-1.9.1.min.js:5
twGetFile                        @ api.js:362
drummerGetFile             @ code.js:386
downloadFile                  @ code.js:1738
getOutlineOpmltext        @ code.js:591
activateThisOutline        @ code.js:900
(anonymous)                  @ code.js:1080
dispatch                          @ jquery-1.9.1.min.js:3
v.handle                          @ jquery-1.9.1.min.js:3

api.js:369 twGetFile: error == {
    "readyState": 4,
    "responseText": "{\n    \"errno\": -2,\n    \"code\": \"NoSuchKey\",\n    \"syscall\": \"open\",\n    \"path\": \"publicFiles/users/PDXProtestNews/TabSmasher.opml\",\n    \"status\": 500\n}",
    "status": 500,
    "statusText": "Internal Server Error"
}

Performed right-click on TabSmasher tab, selected Inspect from pop-up menu. Selected spCloseBox attribute in console, changed attribute from “hidden” to “visible”, saw close control appear on TabSmasher tab. Closed TabSmasher tab, checked remaining tabs, no data loss.

**Comment by scripting** [comment]
@andysylvester -- thanks for this very detailed report. I know what the issue is with this verb, so you don't need to do any further testing. thanks again.
