### ISSUE TITLE
"Show or Hide HTML code in text" deletes attributes in second IMG tag

### ISSUE THREAD

**Issue by sabre23t** [scripting/drummerSupport#144]
If you have the following HTML in a headline:
`<img src="img_girl.jpg" width="500"><img src="img_girl2.jpg" width="500">`

When you press "Show or Hide HTML code in text" twice, the second IMG tag will have all attributes deleted.
`<img src="img_girl.jpg" width="500" ><img="">`

**Comment by scripting** [comment]
@sabre23t -- thanks for this report, I'd like to get this fixed, but I am not the person to do it. 

I _have_ done work on Concord over the years, but all of it is peripheral stuff. I did not write the core code, and honestly I'm afraid to touch it for fear of breaking something. One day I will rewrite the whole thing from scratch so I can maintain it. 

Anyway this is a Concord bug, and the issue should be in its repo. I hope you'll post it there.
