### ISSUE TITLE
Unexpected behavior of blog.opml

### ISSUE THREAD

**Issue by dogzilla100** [scripting/drummerSupport#147]
I've just started with Drummer, so I'm sure the problem is at my end. I wanted to delete the new blog and start over, so I deleted the blog.opml file and created a new version. I expected the published blog to change to the contents of the new blog.opml file. What I'm seeing is the published blog contains the contents of the old blog.opml file with the contents of the new blog.opml file as the latest addition.

Is this the correct result? I'd expect to see my blog.opml file as the total contents of the blog, so am I missing something? 

How should I delete the contents of the blog if I want to start over? 

Can I post photos directly from my Google Photos account? 

Thanks, this looks like a lot of fun.

**Comment by scripting** [comment]
Hi @dogzilla100 — welcome to drummerland. 

What you’re seeing is the result of caching on the server. 

There probably should be a way to tell it to sompletely start over.

I’ll have a look…

**Comment by scripting** [comment]
@dogzilla100 -- what's your twitter username? 

i have a change planned for the product but before doing that I want to empty out your cache.

**Comment by dogzilla100** [comment]
Hey Dave,

Sorry about the delay, off grid a bit.

My Handle is Doggzilla.

I really like your thinking on Drummer. To me, it seems very powerful, but
pretty simple.

**Comment by scripting** [comment]
Okay -- no problem -- I emptied out your cache manually for now, so you should have a clean slate next time you rebuild.

And I have a feature planned for this so you and others won't have this problem in the future. 

I really work to keep things simple. It's a Unix design philosophy basically.

**Comment by BrianPuckett** [comment]
Hi Dave, I (@hungrygarden) am having the same problem as dogzilla.  Would appreciate clearing my cache or let me know when planned change to fix is ready to try.   Been following you for years.  Love love what you are doing . . .Thank you!!!!

**Comment by scripting** [comment]
For future reference, this problem was dealt with in August, but from the reports here, it appears to not be working. 

http://scripting.com/drummer/blog/2021/08/30/175318.html?title=oldSchoolAndCaching

**Comment by scripting** [comment]
@BrianPuckett -- sorry for the problems -- i cleared out your cache manually. please let me know if that fixed the problem.

**Comment by BrianPuckett** [comment]
Thank you, very much.  Here's what I did.

1.  I read your second email first and added the flOldSchoolUseCache to
blog.html attributes and then published.

2. I then saw email about deleting cache.

Frankly I don't think it is displaying the outline in Blog as shown in
Editor

The attached is what I am seeing now in two screen shotsl

Thank you for your help.

**Comment by scripting** [comment]
Is it not working now? I can’t tell from your comment.

**Comment by BrianPuckett** [comment]
I am sorry for being so technically illiterate.  but NO I do not think it
is working.

1. The BLOG shows a lot of posts that are not in the EDITOR

2. The BLOG does not enable the outliner to expand or collapse as I
composed them in the EDITOR.

I've used many versions of your oldschool and drummer outliner under
@hungrygarden and I may have completely messed it up.

Thank you for any assistance.

**Comment by scripting** [comment]
Mayb3 someone else can help or maybe you could provide so

**Comment by BrianPuckett** [comment]
Sorry, I was replying using email and now see that my screen shots did not display.  Attaching them now to see if someone can verify if working properly or not.


![build my blog](https://user-images.githubusercontent.com/97185548/148283233-431ca0be-9974-4359-a303-e54d2ec8977a.jpg)
![main screen editor](https://user-images.githubusercontent.com/97185548/148283235-a33986cb-4aa2-44cc-b3ce-1d23e152a60f.jpg)

**Comment by akaKenSmith** [comment]
@BrianPuckett, I think the screen capture is displaying as Old School typically displays. If a headline entry doesn't have anything indented beneath it, Old School think's that it is meant to be a free-standing paragraph with no title displayed at the left margin.

If a headline entry has something indented beneath it, Old School display the first line as a bolded title and the one or more pieces indented below in Drummer as regular paragraphs, shown at the left margin. If you include a further level of intending, Old School displays that as an indented paragraph.

If I've summarized those traits of Old School display accurately, then I think your screen captures are behaving as expected.

Most Old School display functions do not bring forward the little wedge from Drummer. One exception would be a tweet display, I believe.

**Comment by BrianPuckett** [comment]
> @BrianPuckett, I think the screen capture is displaying as Old School typically displays. If a headline entry doesn't have 

Thank you, yes you summarized correctly.  Just wanted to be sure.  Thank you for taking time/effort.

**Comment by dogzilla100** [comment]
Hi Dave,

Just wanted to verify that the changes you made worked for me. Thanks!

My Super Power is the ability to use software in ways never planned. I've
crashed VAXes, filled Sun hard drives with junk, destroyed Linux systems,
etc. All in ways that weren't forbidden, just in ways the developers never
thought about. Welcome to the club!

Randy Lea
