### ISSUE TITLE
Question about default template

### ISSUE THREAD

**Issue by cro** [scripting/drummerSupport#153]
Greetings,

Why do some of the `href` and `src` links in the default template lack a protocol scheme?  For example:

```
	<link href="//radio3.io/code/pagestyles.css" rel="stylesheet" type="text/css">
	<script src="//radio3.io/code/pagecode.js"></script>
		
	<script src="//fargo.io/code/shared/xml.js"></script>
	<script src="//fargo.io/code/shared/reader.js"></script>
```

**Comment by scripting** [comment]
I don't know why. Pretty sure I wrote the code, so there's your answer. Sorry. ;-)

**Comment by cro** [comment]
The reason I was asking is if you implement the custom domain name via CloudFront and enable SSL, then the browser provides the scheme based on the fetch.  So if the URL was https://clueless.wtf, then the browser will stick `https:` in front of all the URLs without a scheme.  Since you don't serve any of your sites over SSL, it causes the page not to load correctly (or at all).

I'd be happy to open a PR to fix that, I'm not sure if you keep the default template in source control.  I could also use a custom template, but I was hoping not to do that so I wouldn't miss out on any upcoming potential goodness that may or may not be arriving via the default template.

**Comment by cro** [comment]
Well, I tried the custom template route, and am now being bitten by CORS issues and mixed content blocking.  Sigh.  Not sure if I want to go down the CORS rabbit hole, the front-end folks at my work complain about it all the time. 😀

**Comment by scripting** [comment]
There was a lot of discussion about that here on October and November. Look around the issues.
