### ISSUE TITLE
Change of the background image 

### ISSUE THREAD

**Issue by ambiprospect** [scripting/drummerSupport#156]
Where can a POET find how to change the background image for my blog http://oldschool.scripting.com/ahinama/. At present it seem to be urlHeaderImage": "http://scripting.com/images/2021/08/02/joeDiMaggio.png", and I want to change it to the Ukrainian flag.

**Comment by scripting** [comment]
http://docserver.scripting.com/drummer/blogging.opml#1634760877000

**Comment by ambiprospect** [comment]
Thanks Dave for the link! Problem solved, and I think how I solved it may be of interest for other POETS (non-coding users). 
In the File menu I choose Open _OPML Headers_ where I find a table with _Titel_ , _Date created_, and some other attributes. Here I clicked the + under the table and got an empty field in which I entered _urlHeaderImage_ in the left field. Then I opened Scripting News in Windows/Chrome and right-click and choose _View page source_ and searched for "urlHeaderImage": "http://scripting.com/images/2022/02/26/ukraineFlag.png". After copying this link to the right field of the table I choose _Save_ and then I choose _Build my blog_ in the Tools menu. Voila! There my Ukrainian flag appeared as background for my blog SKALMAN.

**Comment by scripting** [comment]
You should read the docs before asking for help.

**Comment by ambiprospect** [comment]
For sure, I agree. But what do you do when you cannot find what you are looking for. What I can contribute is a misunderstanding of the two occasions the term attribute are used. When I read about _Head-level attributes_ I obviously only found the symbol in the left margin (Edit attributes)  which I, in vain, tried to use for the urlHeaderImage. I had totally missed the _Edit OPML Headers ..._in the File menu, which I found today to be the right place to add the urlHeaderImage. Perhaps you should add a similar explanation as you have in the preceding section on _[How to set the title and description of your blog]_ By following this procedure I had no problem to get my new title SKALMAN as expected. I hope you regard this as a constructive suggestion in the spirit of your own ambition to prepare the docs as user-friendly as possible. Keep swinging!
