### ISSUE TITLE
Is Drummer down?

### ISSUE THREAD

**Issue by oevl** [scripting/drummerSupport#165]
```connect ECONNREFUSED 161.35.120.52:1674```

Seems it is a Digital Ocean server.

**Comment by scotthansonde** [comment]
I'm seeing the same error opening http://drummer.scripting.com from my iPhone

**Comment by scripting** [comment]
Drummer should be back up now. Please try again.

**Comment by andysylvester** [comment]
I was able to log in and view outlines directly - thanks!

**Comment by scotthansonde** [comment]
Works for me again as well.
