### ISSUE TITLE
"Error running script: Can't build the blog..."

### ISSUE THREAD

**Issue by akaKenSmith** [scripting/drummerSupport#166]
I composed a blog post for my public blog outline, using the web version of Drummer and starting in the usual way in Chrome from the +, and when I was done writing I clicked on the cloud/arrow button, expecting the little squeak and then to be able to refresh the Old School blog page and see the new post. But instead of the squeak I saw this pop-up item:

<img width="650" alt="Screen Shot 2022-07-05 at 4 24 20 PM" src="https://user-images.githubusercontent.com/4759847/177426889-5083a4a8-0b0e-44b8-8e17-9cd1acc90250.png">

The Old School blog page would not show the new post, too. I went through that usual process a couple more times, with the same result each time.

Then I opened the Developer's Tools and tried a hard reboot a couple of times, but I still got the same result when trying to post to Old School. During those attempts I took a screen capture of a couple of things that popped up on the D T portion of the screen. First this one, then the other one later.

<img width="568" alt="Screen Shot 2022-07-05 at 6 06 29 PM" src="https://user-images.githubusercontent.com/4759847/177427185-a32599d7-4bd9-49bb-80c7-5064a074e0c6.png">

<img width="578" alt="Screen Shot 2022-07-05 at 6 07 08 PM" src="https://user-images.githubusercontent.com/4759847/177427217-e79fd6c7-ee8a-47be-be30-64c271e1f1d2.png">

When I click on Issues, this text appears in the Dev T: "Audit usage of navigator.userAgent, navigator.appVersion, and navigator.platform"

In the OPML header list for this outline, flPublic is marked as True. Just before sending this note here, I ran through the steps to post again, but no change.

Thanks.

**Comment by scripting** [comment]
thanks for the report. please try again.

**Comment by akaKenSmith** [comment]
Looks like it's all working now, thanks.

**Comment by scripting** [comment]
btw that's a shitty error message, but it took me right to the problem, which makes it a great error message. 

the problem wasn't what it said it was, the problem was that i had to reboot the server, and forgot to give the machine permission to make calls to itself over HTTP. If this problem ever comes up again next time i hope i won't forget to do this. (I added a note to my checklist.)

**Comment by mistersugar** [comment]
I am experiencing this same error message when trying to rebuild my blog. 

After I first encountered the error but before I found this issue thread, I deleted my blog.opml file and created a new one using Electric Drummer and I confirmed that the outline was public using Concord Reader (http://scripting.com/code/testing/concordreader/?url=http://drummer.scripting.com/mistersugar/blog.opml)

<img width="259" alt="Screenshot 2023-01-02 at 8 34 13 AM" src="https://user-images.githubusercontent.com/3846301/210238817-8eab7502-d1fe-4c55-9729-f03ab88ee0a5.png">

<img width="471" alt="Screenshot 2023-01-02 at 8 34 04 AM" src="https://user-images.githubusercontent.com/3846301/210238819-d698a15c-d9a9-4e35-bf19-5bb826616333.png">

<img width="554" alt="Screenshot 2023-01-02 at 8 33 57 AM" src="https://user-images.githubusercontent.com/3846301/210238821-b37f08ab-ced2-499b-8df9-9e561452400d.png">

**Comment by scripting** [comment]
@mistersugar -- Thanks for the report... 

i got the report from another user, and just fixed it, i think.

please confirm...

**Comment by mistersugar** [comment]
@scripting I can confirm that I was just able to rebuild the blog. Thanks for fixing.

**Comment by allthisness** [comment]
Fixed 😊 thank you 🙏

**Comment by akaKenSmith** [comment]
I was about to write this up myself but before I could explain it to myself it started rebuilding the blog as expected. Thanks.
