### ISSUE TITLE
Blog file corrupted

### ISSUE THREAD

**Issue by mistersugar** [scripting/drummerSupport#169]
I posted an update to my Drummer blog (http://oldschool.scripting.com/mistersugar/) today, but then the blog.opml file went blank and the tab-closing x disappeared. I followed the [instructions](http://scripting.com/drummer/blog/2021/11/24/142717.html?title=tabWithNoCloseBox) to get the x to close the tab, but another outline that was opened then went blank. I tried other browsers and got this same behavior. I can get all my other outlines open fine, but the blog.opml file is always blank.

In the console, I get errors at the top, then the full contents of what should be in the outline, and more errors. Screenshots follow.

I can't remember how to restore my blog.opml file from my backup. Please advise.

<img width="481" alt="Screen Shot 2022-10-04 at 8 52 04 PM" src="https://user-images.githubusercontent.com/3846301/193963802-9e01019b-3165-45f0-8cd8-a24a5b481306.png">

<img width="466" alt="Screen Shot 2022-10-04 at 8 52 22 PM" src="https://user-images.githubusercontent.com/3846301/193963820-e98c67cc-6839-4400-ae85-78cc6b02cab6.png">

**Comment by scripting** [comment]
@mistersugar -- I checked, there was corruption in the file, I was able to fix it, so try again and let us know what happened.

http://drummer.scripting.com/mistersugar/blog.opml

**Comment by scripting** [comment]
@mistersugar -- did that fix the problem?

**Comment by mistersugar** [comment]
Yes, problem is fixed. We can close this issue.

---
*Anton Zuiker*
919.923.9491

Blogging again at zuiker.com

**Comment by scripting** [comment]
BTW for important work like this, it's smart to use Electric Drummer. That way if a file were to be corrupted, or lost, you could replace it in the file system yourself. You wouldn't be dependent on me being there to do it for you.

All you have to do is create a file called blog.opml locally, and make it public. It'll be in the right place for Old School to find it. That's how I do my blog work.

**Comment by mistersugar** [comment]
Working again as expected and I was able to post a short item to the blog.

Thank you!

---
*Anton Zuiker*
919.923.9491

Blogging again at zuiker.com
