### ISSUE TITLE
Error when ‘Building Blog’

### ISSUE THREAD

**Issue by allthisness** [scripting/drummerSupport#170]
I started a Drummer blog just before Xmas at:
http://oldschool.scripting.com/allthisness/

It’s been working fine until yesterday when I made a new post then went to Build My Blog and got this error dialogue.

![AB2D9CEE-CE91-4A9E-BDC7-42F5089254BD](https://user-images.githubusercontent.com/121541188/210240221-b9eb1862-8b13-4820-b74a-96133096a011.png)

Any ideas as it’s been working fine up to now?

**Comment by akaKenSmith** [comment]
I believe this has been addressed in the last day or so. I would try again now.

**Comment by scripting** [comment]
Thanks for checking this Ken. He was following another thread, and got it working. I'll close the issue now.
