### ISSUE TITLE
Drummer Stops Saving Tab/Outline

### ISSUE THREAD

**Issue by fmcpherson** [scripting/drummerSupport#187]
I have had two recent instances in which Drummer stopped saving any changes that I made to an outline in a tab. In both instances I was writing a large post, in the most recent the post had seven paragraphs. Each paragraph is a child of parent node that is the title of the post and was part of my blog.opml file. (See the last screenshot below).

I noticed the problem after writing the blog post, publishing the post by clicking Tools, Build my blog, reading the post and finding an error that I returned to Drummer to correct. I made the edit, clicked Tools, Build my blog, looked at the published result and saw that the change did not publish. I then returned to Drummer made another edit and watched the Saved/Not Saved indicator and saw that it always stayed at Not Saved no matter whether I made a change or expanded or collapsed the title/parent node. 

I then opened the browser console and captured this screenshot:

<img width="984" alt="DrummerNotSaving" src="https://user-images.githubusercontent.com/7051925/231240440-198056e2-fa0f-472a-be08-b9e994266892.PNG">

To resolve, I shut down Chrome and restarted, then reloaded Drummer, which opened my blog.opml. I then expanded/collapsed the title node a few times and watched the Not Saved/Saved indicator. I then edited the blog post, clicked Tools, Build my blog and noticed that the blog post published as expected. 

I captured the following screenshot of the browser console while Not Saved/Saved indicated as expected. 

<img width="984" alt="DrummerSaving" src="https://user-images.githubusercontent.com/7051925/231241155-9571fae1-3dd2-4a6d-85f1-b4180042a14a.png">

**Comment by scripting** [comment]
@fmcpherson -- from the error messages you're getting it looks like there may be a problem with communicating with the server.

so before assuming it's a problem with the outliner, you should check that out. do you have any plug-ins installed, are you running on a network with firewalls that could be interfering. any other software having problems? does the problem persist?
