### ISSUE TITLE
Error on Sign Up: Can't create the user "{email}" because only alpha, numeric and underscore characters are allowed in names.

### ISSUE THREAD

**Issue by brandon-toner** [scripting/drummerSupport#188]
I'm trying to create an account on Drummer using the "Signup with Drummer" button, but it is returning an error.

Dialog: "Email address to send confirmation to:"
My Input: "[toner.brandon@gmail.com](mailto:toner.brandon@gmail.com)"
Error: "Can't create the user "[toner.brandon@gmail.com](mailto:toner.brandon@gmail.com)" because only alpha, numeric and underscore characters are allowed in names."

I've also tried to "Sign In" in case my email was already registered, but after clicking the link in my email it confirms that I do not already have an account.

Is this a known issue with the Sign Up?

**Comment by scripting** [comment]
@brandon-toner -- i did what you did, and it appears to have worked. Here's a screen shot.

<img width="601" alt="image" src="https://user-images.githubusercontent.com/1686843/231551853-cd0aa6b4-5679-4225-afc6-66bef991f9c6.png">

You should have gotten an email.

**Comment by brandon-toner** [comment]
Odd — I never did get that pop-up window. It only asked me for an email address. I did get the email now. 

FeedLand shows me signed in, but I don't see a "user profile" to confirm that my email is registered. 

After that — I opened Drummer and tried to sign in again. It collected my email and sent a "confirmation email", which I got. 

The email link took me to a message that said "Welcome to the camp!".

When I reopened Drummer, I was still not signed in.

**Comment by brandon-toner** [comment]
@scripting — Did you see my followup comment? The issue doesn't appear to be resolved on my end.

**Comment by brandon-toner** [comment]
Here is a recording of what happens when I try to "sign up" on Drummer:
![Screen Recording of Problem](https://user-images.githubusercontent.com/67168828/232049324-974138a8-0b76-45a6-904f-5451b342b32c.gif)

Here is the message I receive after trying to "sign in" to Drummer (no account):
<img width="587" alt="CleanShot 2023-04-14 at 09 53 38@2x" src="https://user-images.githubusercontent.com/67168828/232049317-e0e11797-ce35-4063-b2c8-cad606693b78.png">

Feedland works on sign in since my email was added in the above step by @scripting.

Tested on Arc, Chrome, and Firefox.

**Comment by scripting** [comment]
@brandon-toner -- thanks for the report. please try again, i believe the problem is fixed.

**Comment by brandon-toner** [comment]
All good now! That fixed it. Signed up and logged in successfully in browser and in app 😎
