### ISSUE TITLE
Make outline public... returns "return404 is not a function"

### ISSUE THREAD

**Issue by afscott56** [scripting/drummerSupport#196]
I an a longtime user of LittleOutliner and have now moved all of my OPML files to Drummer. I often use the outlines as lecture note as it provides for the easy use of links that can be reordered with all the ease that an outliner provides. 

Once the lecture was given I would publish the list (using the "Make outline public..." function in the file menu) in the educational system that was in use at the time. Just what I needed and it never failed me - until now.

Now the Make outline public function returns "return404 is not a function" when the link is pasted into a browser. Is there something I am missing or has this functionality stopped working?

**Comment by scripting** [comment]
In order to investigate we need steps to reproduce the problem. 

I just tried the _Make outline public_ command here and it worked. 

So try it with a new file, and write down each of the steps, 1, 2, 3, let us know.

Can't debug it unless we can reproduce it.

**Comment by afscott56** [comment]
1. Make new outline "Test publish"
2. Create som simple content
3. Choose "Make outline public..."
4. Copy the link in the dialogue window that appears
5. Paste the link into a new browser window
6. Get "return404 is not a function" response

**Comment by scotthansonde** [comment]
I was not able to reproduce this behavior
1. I created an outline testPublish.opml
2. I added some content
3. I chose "Make outline public"
4. I copied the given URL https://drummer.land/papascott@gmail.com/testPublish.opml
5. I pasted the URL into a new browser window
6. The URL opened as expected (as an unstyled XML file in Chrome)

**Comment by scripting** [comment]
@scotthansonde -- thanks for verifying the test.

@afscott56 -- we need the URL from your step 4.

**Comment by afscott56** [comment]
from step 4: https://drummer.land/ansc@du.se/test publish.opml

I notice that Scott doesn't have a space between "test" and "publish" but I do. I made an outline called simply "test", used the "Make outline public" menu command and pasted it into a browser window (https://drummer.land/ansc@du.se/test.opml). The result was better but not what I was used to getting from LittleOutliner 1 & 2. This time I got "This XML file does not appear to have any style information associated with it. The document tree is shown below" as well as the afore mentioned document tree.

During this time I noticed the post in the file menu called "Open URL". I used this with the link I had copied and it worked perfectly within Drummer. My problem is that I cannot expect my students to use Drummer and need the link to work as an ordinary link in an ordinary browser.

Thinking about this I tried to use the "Open URL" command with "https://drummer.land/ansc@du.se/test publish.opml". this time the system returned "Can't open the outline because we couldn't read the file". Not being a programmer of any description I realise that my naming strategies are not optimal for Drummer. And now I also realise that I have no idea where these opml files are stored! 

I was always fascinated by how the LittleOutliner links were so simple. Not wanting to break something that was working I didn't think about it and just used it. I have been looking around for other outliners that can publish to the web but not found anything yet.

I am a longtime follower of Dave/Scripting/Userland and have really benefitted from this simple function. I do hope it is something that I am not doing right that is the problem and I can go back to using this great tool!

**Comment by scripting** [comment]
In general don't use spaces in file names to avoid situations like this. 

This is the command to launch Drummer with a specific file open.

https://drummer.land/?url=https://drummer.land/ansc@du.se/test.opml

Also before asking for more help, please [read this](http://scripting.com/2014/03/19/howToAskForHelpWithSoftware.html) and take it to heart. Thanks.

**Comment by afscott56** [comment]
Thanks for the help! Everything is working for me now. /Anderw
