### ISSUE TITLE
Are you using Drummer to post tweets?

### ISSUE THREAD

**Issue by scripting** [scripting/drummerSupport#34]
If so, please post a link to a tweet in this thread.

I'd like to see! :smile:

Dave

**Comment by dixonge** [comment]
So this changed I guess - I don't get a wedge, just a Twitter icon. Text only, no Twitter preview box...

**Comment by scripting** [comment]
@dixonge -- I take it very seriously when someone says my software has broken. I have a lot of users and I really care about them, and I take pride in my work. So after a while if you keep ringing the bell like that, you're not going to get a response at all.

**Comment by dixonge** [comment]
> @dixonge -- I take it very seriously when someone says my software has broken. I have a lot of users and I really care about them, and I take pride in my work. So after a while if you keep ringing the bell like that, you're not going to get a response at all.

So misunderstanding something = 'ringing the bell'??? Wow. You know what? Don't worry about responses. I'll find better tools to use. Should take about 5 minutes...
