### ISSUE TITLE
Unable to build the blog

### ISSUE THREAD

**Issue by am1t** [scripting/drummerSupport#58]
I have followed the steps as per the documentation.

**Steps Followed:**
1. Created a new "blog.opml" file.
2. Added some content.
3. Made the outline public. Available at [this link](http://drummer.scripting.com/_am1t/blog.opml).
4. Clicked "Build my blog" in tools section.

**Expected Behaviour:** A new page with the blog content opens.
**Observed Behaviour:** A new page with "The file name contains illegal characters." opens. The URL is `http://oldschool.scripting.com/_am1t/blog.opml`.

Does it have issue with the underscore and a number in my Twitter handle?

**Comment by scripting** [comment]
@am1t -- I'm still not sure what happened to, and to what extent your blog is working. But this URL now works.

http://oldschool.scripting.com/_am1t/

I don't believe blog.opml is copied into that folder, so you said it couldn't open the file and that actually is correct, even though it gave the wrong reason. ;-)

#### Try going through the Hello World steps again and see what happens.

I had to change the configuration on the server for it not to see _ as an illegal character, and then there was another problem, for some reason it thought a file beginning with _ is a hidden file. 

So thank you -- you're helping us get some bugs out. First-day issues. :-)
