### ISSUE TITLE
Working example of Radio3 bookmarklet

### ISSUE THREAD

**Issue by jackbaty** [scripting/drummerSupport#71]
I was unable to get the "R3" bookmarklet provided in the [Radio3 HowTo](http://this.how/radio3/) to work, so I asked around and John Johnston (@troutcolor) had a working version available, which he shared [here](https://gist.githubusercontent.com/troutcolor/37af0206d667ab5cb795248576f4e183/raw/2a72872c31faf493f00de23c67c8bc3c59e2c3a6/R3.js)

Or TL;DR:

```
javascript:(function()%7B%20window.open('http://radio3.io/?link='+encodeURIComponent(location.href)+'&title='+encodeURIComponent(document.title)+'&description='+encodeURIComponent(document.getSelection()));%20%7D)();
```

I heard at least one or two others have had trouble with the bookmarklet, so hopefully, this gets you by, as I can't imagine it being a priority for Dave right now.

This may not be the proper Github project for this issue, but I think the Radio3 integration with Drummer is a great feature, so I think it makes some sense here.

**Comment by frankmeeuwsen** [comment]
Just a quick add-on, in the above code some characters are encoded. In my version of Firefox what works is

`javascript:(function(){window.open('http://radio3.io/?link='+encodeURIComponent(location.href)+'&title='+encodeURIComponent(document.title)+'&description='+encodeURIComponent(document.getSelection()));})();`

**Comment by jackbaty** [comment]
Yes, I was copying the bookmarklet from http://this.how/radio3/, so if that version was correct I would've been all set. Thanks!
