### ISSUE TITLE
Webmention support on Drummer?

### ISSUE THREAD

**Issue by frankmeeuwsen** [scripting/drummerSupport#85]
Since it's better to post about it on your own blog than just leave it here, I posted some questions on the use of Webmentions on Drummer on [my own Drummerblog](http://frankmeeuwsen.xyz/2021/10/19/143852.html?title=webmentionsOnDrummer). I am not tech savvy enough to see what could be possible and howm but I have the feeling webmentions, OPML and outliners can be a perfect match. 
I look forward to discussing the possibilities. This is not an actual issue or bug, rather a thread to discuss and explore.

**Comment by frankmeeuwsen** [comment]
Well...here's the funny thing. I wrote about it on my blog. But since Drummer doesn't have comments, others can't contribute. Unless they write on their own blog and link to my blog. That's where webmentions can be a valuable building block. 
With webmentions I could link in my post to others like Jack Baty and Andy Sylvester. That's how you can build a community from your own blog. Make others aware of your writing and the questions you ask. I am well aware of the possible dangers as well. Webmentions, comments, pingbacks, they all have their drawbacks. But what are the alternatives to build a conversation on your domain?

**Comment by scripting** [comment]
@frankmeeuwsen -- this site is for support, for helping people with problems they are having using Drummer. I'm not going to argue with you about this. You can build a community for your blog, but you can't use the support forum here to do that.
