### ISSUE TITLE
After closing all tabs, unable to open last outline closed

### ISSUE THREAD

**Issue by papascott** [scripting/drummerSupport#89]
Here's the scenario: I open Drummer with two tabs open, 'notes' and 'notes2'. I first close 'notes2', then I close 'notes'. I go to the open dialog, but 'notes' is not listed as a file I can open, only 'notes2'. When I reload, Drummer restarts with 'notes' open.

I made a screencast:

https://user-images.githubusercontent.com/8681117/138075836-8637b77a-927e-4db1-a0e2-1a3049c1a5c1.mp4

**Comment by scripting** [comment]
@papascott -- thanks for the report. 😀

I found and fixed the problem. There's a [change note](http://scripting.com/drummer/blog/2021/10/20/130435.html?title=fileopenListBugFixed) for it.
