### ISSUE TITLE
Unreadable popup dialog after clicking on the retweet button

### ISSUE THREAD

**Issue by dcoletta** [scripting/drummerSupport#90]
Steps to repro:
- Go to cannabiscto.com
- Click on any retweet button
- See popup asking if I want to sign into Twitter
- Complete Twitter sign in
- Click on retweet button again

Expected:
- Confirmation dialog? Not sure exactly what happens next

Actual:
<img width="627" alt="Screen Shot 2021-10-20 at 7 49 19 AM" src="https://user-images.githubusercontent.com/169427/138087151-436c5ad5-9ead-4e10-90bd-684239c1976d.png">
:

**Comment by dcoletta** [comment]
And I see this error in the console. (Obviously related to hosting over https.)
```
readHttpFileThruProxy: url == http://fargo.io/code/shared/tweeteditor.html, error == error.
```

**Comment by scripting** [comment]
it's not a bug in my software, i did not take on that project i just said it was okay with me if you all wanted to do it. in other words, it's not my problem. ;-)
